apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: environment-credentials
  namespace: ft
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: environment-credentials
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: .*
