apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: environment-credentials
  namespace: ft
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: environment-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ft/app
