apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-configs
  namespace: ft
data:
  DOMAIN: template.local
  FRONTEND_HOST: http://app.template.local
  ENVIRONMENT: staging
  PROJECT_NAME: "Full Stack FastAPI Template"
  STACK_NAME: "full-stack-fastapi-template"
  BACKEND_CORS_ORIGINS: '["http://app.template.local:8080", "http://localhost:5173"]'

  SMTP_HOST: ""
  EMAILS_FROM_EMAIL: "teste@example.com"
  SMTP_TLS: "True"
  SMTP_SSL: "False"
  SMTP_PORT: "587"

  # POSTGRES_SERVER: ""
  # POSTGRES_PORT: ""
  # POSTGRES_DB: "app"
  # POSTGRES_USER: "postgres"
  # POSTGRES_PASSWORD: ""
  
