apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: local
servers: 1
agents: 2
image: rancher/k3s:v1.33.10-k3s1
kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6443"
ports:
  - port: 8080:80
    nodeFilters: [loadbalancer]
  - port: 8443:443
    nodeFilters: [loadbalancer]
hostAliases:
  - ip: 127.0.0.1
    hostnames:
      - app.template.local
      - api.template.local
      - bao.local
      - vaultwarden.local
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
options:
  k3d:
    wait: true
    timeout: "120s"
    disableLoadbalancer: false
    disableImageVolume: false
  k3s:
    extraArgs:
      - arg: "--tls-san=127.0.0.1"
        nodeFilters: [server:*]
    nodeLabels:
      - label: bytewer.io/role=worker
        nodeFilters: [agent:*]
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
